### ISSUE TITLE
Error using Collection array with @mui/material Checkbox

### ISSUE THREAD

**Issue by lrkwz** [iusehooks/usetheform#42]
When I use `<Collection />` of type array build around some `<Checkbox />` I receive the following error:

    The prop "name": apple of type "string" passed to "<Input />" it is not allowed within context a of type "array".

See https://codesandbox.io/s/collection-array-with-mui-checkbox-values-zh1sv and try to replace `object` with `array`

**Comment by iusehooks** [comment]
As documentation says: 

**If your Collection is rendered within a <Collection array />, name is not allowed as a prop.**

https://iusehooks.github.io/usetheform/docs-collection

What are you trying to achieve? which is the output expected?

**Comment by lrkwz** [comment]
I expected the output to be `["apple", "banana", "pineapple"]`.

your example outputs `{"myPreferredFruit":[null,true,true]}`.

If you add the `value` prop to each of the `Checkbox`es the result is even stranger being `{"myPreferredFruit":["apple","banana",true]}` (why doeas the last one have value `true` instead of `pineapple`?).

BTW what is `withIndex`? I didn't find it in th docs.

**Comment by iusehooks** [comment]
If you want to get back a spefic value instead of true/false from a checkbox you have to pass that value as prop to the checkbox.

Working example at: https://codesandbox.io/s/collection-array-with-mui-checkbox-values-forked-bigzk?file=/src/components/Checkbox.js

You can read about withIndex at: https://iusehooks.github.io/usetheform/docs-collection#array-collection

Thanks.

**Comment by lrkwz** [comment]
Thank you!
